#!/usr/bin/env python3
"""生成发布版 requirements.txt（确定性裁剪 pyside6/pyside6-addons）。

uv.lock 是依赖的唯一来源（AGENTS.md）。本脚本从 uv.lock 导出 Windows 平台依赖清单，
再裁剪 pyside6 / pyside6-addons（qfluentwidgets 依赖 PySide6 元包引入，含
QtWebEngine 约 200MB），发布包只保留 pyside6-essentials。配合 pyappify.yml 的
pip_args "--no-deps"，用户端 pip 只按本清单精确安装，不再拉取 QtWebEngine。

    生成并覆盖 requirements.txt：
      uv run --locked python scripts/release/gen_release_requirements.py

    校验已提交的 requirements.txt 与生成结果一致（CI 使用）：
      uv run --locked python scripts/release/gen_release_requirements.py --check
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

try:
    from packaging.markers import Marker
except ImportError:
    Marker = None  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "requirements.txt"

DROPPED_PKGS = {"pyside6", "pyside6-addons"}

# 目标发布平台：Windows x64 + Python 3.12
WINDOWS_ENV = {
    "os_name": "nt",
    "sys_platform": "win32",
    "platform_machine": "AMD64",
    "platform_python_implementation": "CPython",
    "platform_release": "10",
    "platform_system": "Windows",
    "platform_version": "10.0.19045",
    "python_full_version": "3.12.10",
    "python_version": "3.12",
    "implementation_name": "cpython",
}

HEADER = """\
# This file was autogenerated from uv.lock via the following command:
#    uv run --locked python scripts/release/gen_release_requirements.py
# NOTE: 发布裁剪 - pyside6 / pyside6-addons（含 QtWebEngine，约 200MB）已从本文件
# 移除，仅保留 pyside6-essentials。配合 pyappify.yml 的 pip_args "--no-deps"，
# 用户端 pip 只按本清单精确安装，不再拉取 QtWebEngine。
# 重新生成：
#   uv run --locked python scripts/release/gen_release_requirements.py
# 校验（CI）：
#   uv run --locked python scripts/release/gen_release_requirements.py --check
"""


def generate_compiled() -> str:
    """从 uv.lock 导出 requirements 格式清单（与锁文件版本一致，不含 dev 组）。"""
    cmd = ["uv", "export", "--locked", "--format", "requirements-txt", "--no-hashes", "--no-dev"]
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, encoding="utf-8")
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"uv export 失败: rc={proc.returncode}")
    return proc.stdout


def marker_applies(marker: str | None) -> bool:
    """判断环境标记是否适用于 Windows x64 + Python 3.12（解析失败时终止，不静默放行）。"""
    if not marker:
        return True
    if Marker is None:
        raise SystemExit("packaging.markers 不可用，无法解析依赖标记")
    try:
        return bool(Marker(marker).evaluate(WINDOWS_ENV))
    except Exception as exc:
        raise SystemExit(f"依赖标记解析/求值失败: {marker!r} ({exc})") from exc


def shrink(compiled: str) -> str:
    """按平台过滤条目，去掉 pyside6/pyside6-addons，并清理 via 引用。"""
    lines = compiled.splitlines()
    start = 0
    while start < len(lines) and (lines[start].startswith("#") or not lines[start].strip()):
        start += 1

    via_dropped: set[str] = set(DROPPED_PKGS)
    result: list[str] = [HEADER]
    i = start
    n = len(lines)
    while i < n:
        line = lines[i]
        if not line.strip() or line.startswith("#"):
            i += 1
            continue
        j = i + 1
        block = [line]
        while j < n and lines[j].startswith(" "):
            block.append(lines[j])
            j += 1
        head = block[0]
        marker = ""
        if ";" in head:
            pkg_part, marker = head.split(";", 1)
            marker = marker.strip()
            head = pkg_part.rstrip()
        pkg = head.split("==", 1)[0]
        if pkg in DROPPED_PKGS or not marker_applies(marker):
            via_dropped.add(pkg)
            i = j
            continue
        kept = [head]
        for bl in block[1:]:
            via_ref = bl.strip().removeprefix("#").strip().removeprefix("via ").strip()
            if via_ref in via_dropped:
                continue
            kept.append(bl)
        result.extend(kept)
        i = j
    return "\n".join(result) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(OUTPUT), help="输出文件路径")
    parser.add_argument("--check", action="store_true", help="校验已提交文件与生成结果一致")
    args = parser.parse_args()

    output = Path(args.output).resolve()
    if not output.is_relative_to(ROOT):
        sys.stderr.write(f"输出路径必须在仓库内: {output}\n")
        return 1

    generated = shrink(generate_compiled())

    if args.check:
        if not output.exists():
            sys.stderr.write(f"缺少文件: {output}\n")
            return 1
        current = output.read_bytes()
        if current != generated.encode("utf-8"):
            sys.stderr.write("requirements.txt 与生成结果不一致，请重新生成:\n")
            sys.stderr.write("  uv run --locked python scripts/release/gen_release_requirements.py\n")
            return 1
        print("OK: requirements.txt 与生成结果一致")
        return 0

    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"已生成 {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
